name: check_new_release
run-name: Check new Zabbix release

on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:

env:
  BRANCHES_URL: https://git.zabbix.com/rest/api/1.0/projects/ZBX/repos/zabbix/branches
  LIBREPO_URL: https://github.com/leroylim/typescript-zabbix-utils
  MANUAL_REPO: https://github.com/leroylim/typescript-zabbix-utils/blob/main/UPSTREAM_SYNC.md

jobs:
  check:
    name: Check new release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build TypeScript
        run: npm run build
      - name: Check for new Zabbix release
        env:
          BRANCHES_URL: ${{ env.BRANCHES_URL }}
          LIBREPO_URL: ${{ env.LIBREPO_URL }}
          MANUAL_REPO: ${{ env.MANUAL_REPO }}
        run: |
          node ./.github/scripts/check_new_zabbx_release.js
