name: zabbix_latest
run-name: Compatibility with the latest Zabbix version test
on:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:

env:
  ZABBIX_VERSION: 'latest'
  ZABBIX_BRANCH: master
  CONFIG_PATH: .github/configs/
  TEST_FILE: compatibility_api_test_latest.js

jobs:
  compatibility:
    name: Compatibility test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install packages
        run: |
          sudo apt update && sudo apt install -y git sudo gcc make automake pkg-config postgresql-16 libpostgresql-ocaml-dev libxml2-dev libpcre3-dev libevent-dev apache2 libapache2-mod-php php8.3-pgsql php8.3-bcmath php8.3-xml php8.3-gd php8.3-ldap php8.3-mbstring libzip-dev
      - name: Build from sources
        run: |
          WORKDIR=$(pwd)
          cd /tmp/
          sudo addgroup --system --quiet zabbix
          sudo adduser --quiet --system --disabled-login --ingroup zabbix --home /var/lib/zabbix --no-create-home zabbix
          git -c advice.detachedHead=false clone https://git.zabbix.com/scm/zbx/zabbix.git --branch ${{ env.ZABBIX_BRANCH }} --depth 1 --single-branch /tmp/zabbix-branch
          cd /tmp/zabbix-branch
          ./bootstrap.sh
          ./configure --enable-server --enable-agent --with-postgresql
          sudo make dbschema_postgresql
          sudo make
          echo -e "CacheUpdateFrequency=1\n" >> ./conf/zabbix_server.conf
          ./configure --enable-proxy --with-sqlite3
          sudo make
          mkdir /tmp/zabbix_proxy1/
          mkdir /tmp/zabbix_proxy2/
          cp ./conf/zabbix_proxy.conf ./conf/zabbix_proxy1.conf
          mv ./conf/zabbix_proxy.conf ./conf/zabbix_proxy2.conf
          sed -i "s/Hostname=Zabbix proxy/Hostname=CompatibilitySenderTest_proxy1/g" ./conf/zabbix_proxy1.conf
          sed -i "s/Hostname=Zabbix proxy/Hostname=CompatibilitySenderTest_proxy2/g" ./conf/zabbix_proxy2.conf
          sed -i "s#LogFile=/tmp/zabbix_proxy.log#LogFile=/tmp/zabbix_proxy1.log#g" ./conf/zabbix_proxy1.conf
          sed -i "s#LogFile=/tmp/zabbix_proxy.log#LogFile=/tmp/zabbix_proxy2.log#g" ./conf/zabbix_proxy2.conf
          sed -i 's#DBName=zabbix_proxy#DBName=/tmp/proxy1.db#' ./conf/zabbix_proxy1.conf
          sed -i 's#DBName=zabbix_proxy#DBName=/tmp/proxy2.db#' ./conf/zabbix_proxy2.conf
          echo -e "PidFile=/tmp/zabbix_proxy1/zabbix_proxy1.pid\n" >> ./conf/zabbix_proxy1.conf
          echo -e "PidFile=/tmp/zabbix_proxy2/zabbix_proxy2.pid\n" >> ./conf/zabbix_proxy2.conf
          echo -e "SocketDir=/tmp/zabbix_proxy1\n" >> ./conf/zabbix_proxy1.conf
          echo -e "SocketDir=/tmp/zabbix_proxy2\n" >> ./conf/zabbix_proxy2.conf
          echo -e "ListenPort=10061\n" >> ./conf/zabbix_proxy1.conf
          echo -e "ListenPort=10062\n" >> ./conf/zabbix_proxy2.conf
          sudo chown -R zabbix:zabbix /tmp/zabbix_proxy1/
          sudo chown -R zabbix:zabbix /tmp/zabbix_proxy2/
          cd ui
          sudo rm /var/www/html/index.html
          sudo cp -a . /var/www/html/
          sudo cp $WORKDIR/${{ env.CONFIG_PATH }}/zabbix.conf.php /var/www/html/conf/
          sudo cp $WORKDIR/${{ env.CONFIG_PATH }}/pg_hba.conf /etc/postgresql/16/main/pg_hba.conf
          sudo chown -R www-data:www-data /var/www/html/
          sudo sed -i "s/post_max_size = 8M/post_max_size = 16M/g" /etc/php/8.3/apache2/php.ini
          sudo sed -i "s/max_execution_time = 30/max_execution_time = 300/g" /etc/php/8.3/apache2/php.ini
          sudo sed -i "s/max_input_time = 60/max_input_time = 300/g" /etc/php/8.3/apache2/php.ini
          sudo locale-gen en_US.UTF-8
          sudo update-locale
      - name: Prepare environment
        run: |
          sudo mkdir -p /var/run/postgresql/16-main.pg_stat_tmp
          sudo touch /var/run/postgresql/16-main.pg_stat_tmp/global.tmp
          sudo chmod 0777 /var/run/postgresql/16-main.pg_stat_tmp/global.tmp
          (sudo -u postgres /usr/lib/postgresql/16/bin/postgres -D /var/lib/postgresql/16/main -c config_file=/etc/postgresql/16/main/postgresql.conf)&
          sleep 5
          cd /tmp/zabbix-branch/database/postgresql
          sudo -u postgres createuser zabbix
          sudo -u postgres createdb -O zabbix -E Unicode -T template0 zabbix
          cat schema.sql | sudo -u zabbix psql zabbix
          cat images.sql | sudo -u zabbix psql zabbix
          cat data.sql | sudo -u zabbix psql zabbix
          sudo apache2ctl start
      - name: Start Zabbix server
        run: |
          cd /tmp/zabbix-branch
          sudo ./src/zabbix_server/zabbix_server -c ./conf/zabbix_server.conf
      - name: Start Zabbix proxies
        continue-on-error: true
        run: |
          cd /tmp/zabbix-branch
          sudo ./src/zabbix_proxy/zabbix_proxy -c ./conf/zabbix_proxy1.conf
          sudo ./src/zabbix_proxy/zabbix_proxy -c ./conf/zabbix_proxy2.conf          
      - name: Start Zabbix agent
        run: |
          cd /tmp/zabbix-branch
          sudo ./src/zabbix_agent/zabbix_agentd -c ./conf/zabbix_agentd.conf
      - name: Install Node.js
        run: |
          sudo apt-get install -y nodejs npm
          npm ci
      - name: Build TypeScript
        run: |
          npm run build
      - name: Wait for Zabbix API
        run: |
          node ./.github/scripts/wait_instance_zabbix.js
      - name: Print Zabbix version
        continue-on-error: true
        run: |
          grep -Po "(?<=Changes for ).*$" /tmp/zabbix-branch/ChangeLog 2>/dev/null | head -n1
      - name: Compatibility test
        continue-on-error: true
        run: |
          node ./.github/scripts/$TEST_FILE >/tmp/compatibility.log 2>&1
      - name: Send report
        env:
          TBOT_TOKEN: ${{ secrets.TBOT_TOKEN }}
          TBOT_CHAT: ${{ secrets.TBOT_CHAT }}
          SUBJECT: Compatibility with Zabbix ${{ env.ZABBIX_VERSION }} FAIL
        run: |
          tail -n1 /tmp/compatibility.log | grep "OK" 1>/dev/null || tail /tmp/compatibility.log | node ./.github/scripts/telegram_msg.js | exit 1
