name: coverage
run-name: Check test coverage

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  coverage:
    name: Check coverage
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Node.js 18
      uses: actions/setup-node@v4
      with:
        node-version: "18"
        cache: 'npm'
    - name: Install dependencies
      run: |
          npm ci
    - name: Test with coverage
      run: |
          npm run test:coverage
