name: sender
run-name: Zabbix sender integration test

on:
  push:
    branches: [main]
    paths:
      - '**sender.ts'
      - '**aiosender.ts'
  pull_request:
    branches: [main]
    paths:
      - '**sender.ts'
      - '**aiosender.ts'
  workflow_dispatch:

env:
  ZABBIX_VERSION: '6.0'
  ZABBIX_BRANCH: master
  CONFIG_PATH: .github/configs/
  SYNC_FILE: integration_sender_test.js
  ASYNC_FILE: integration_aiosender_test.js

jobs:
  integration:
    name: Integration test
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - name: Install packages
        run: |
          sudo wget https://repo.zabbix.com/zabbix/${{ env.ZABBIX_VERSION }}/ubuntu/pool/main/z/zabbix-release/zabbix-release_${{ env.ZABBIX_VERSION }}-4+ubuntu22.04_all.deb
          sudo dpkg -i zabbix-release_${{ env.ZABBIX_VERSION }}-4+ubuntu22.04_all.deb
          sudo apt update && sudo apt install -y zabbix-proxy-sqlite3
      - name: Prepare environment
        run: |
          sudo mkdir -p /var/log/zabbix/
          sudo chown -R zabbix. /var/log/zabbix/
          sudo sed -i 's#DBName=zabbix_proxy#DBName=/tmp/proxy.db#' /etc/zabbix/zabbix_proxy.conf
      - name: Start Zabbix proxy
        run: |
          sudo zabbix_proxy -c /etc/zabbix/zabbix_proxy.conf
      - name: Install Node.js
        run: |
          sudo apt-get install -y nodejs npm
          npm ci
      - name: Build TypeScript
        run: |
          npm run build
      - name: Sync integration test
        continue-on-error: true
        run: |
          node ./.github/scripts/$SYNC_FILE >/tmp/integration_sync.log 2>&1
      - name: Async integration test
        continue-on-error: true
        run: |
          node ./.github/scripts/$ASYNC_FILE >/tmp/integration_async.log 2>&1
      - name: Send report
        env:
          TBOT_TOKEN: ${{ secrets.TBOT_TOKEN }}
          TBOT_CHAT: ${{ secrets.TBOT_CHAT }}
          SUBJECT: Zabbix sender integration test FAIL
        run: |
          err=0
          tail -n1 /tmp/integration_sync.log | grep "OK" 1>/dev/null || tail /tmp/integration_sync.log | node ./.github/scripts/telegram_msg.js 2>/dev/null | err=1
          tail -n1 /tmp/integration_async.log | grep "OK" 1>/dev/null || tail /tmp/integration_async.log | node ./.github/scripts/telegram_msg.js 2>/dev/null | err=1
          if [ "$err" = 1 ]; then exit 1; fi
