name: release
run-name: Release new version

on:
  push:
    branches: [main]
    paths:
      - '**version.ts'
  workflow_dispatch:

jobs:
  release:
    name: Release new version
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies
        run: npm ci
      - name: Build TypeScript
        run: npm run build
      - name: Set version env
        run: |
          echo "LIBRARY_VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV
      - name: Add version tag
        uses: pkgdeps/git-tag-action@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_repo: ${{ github.repository }}
          git_commit_sha: ${{ github.sha }}
          version: ${{ env.LIBRARY_VERSION }}
          git_tag_prefix: "v"
      - name: Create npm package
        run: |
          npm pack
      - name: Archive built packages
        uses: actions/upload-artifact@v4
        with:
          name: Archive-v${{ env.LIBRARY_VERSION }}
          path: |
            dist/*
            *.tgz
      - name: Create release notes
        run: |
          grep -Pzo '(?s)^## \[${{ env.LIBRARY_VERSION }}\].*?(?=## \[)' CHANGELOG.md | sed '$ s/.$//' > RELEASE_NOTES.md || echo "Release [v${{ env.LIBRARY_VERSION }}]" > RELEASE_NOTES.md
          sed -i 's/\[${{ env.LIBRARY_VERSION }}\]/Release [v${{ env.LIBRARY_VERSION }}]/' RELEASE_NOTES.md
      - name: Create release
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: v${{ env.LIBRARY_VERSION }}
          draft: true
          prerelease: false
          makeLatest: true
          skipIfReleaseExists: true
          replacesArtifacts: true
          removeArtifacts: true
          tag: "v${{ env.LIBRARY_VERSION }}"
          bodyFile: RELEASE_NOTES.md
          artifacts: |
            dist/*
            *.tgz
      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Send notification
        run: |
          node ./.github/scripts/release_notification.js
        working-directory: ./
        env:
          MAIL_SERVER: ${{ secrets.MAIL_SERVER }}
          MAIL_PORT: ${{ secrets.MAIL_PORT }}
          MAIL_USER: ${{ secrets.MAIL_USER }}
          MAIL_PASS: ${{ secrets.MAIL_PASS }}
          RELEASE_RECIPIENT_LIST: ${{ secrets.RELEASE_RECIPIENT_LIST }}
          LIBRARY_VERSION: ${{ env.LIBRARY_VERSION }}
          REPOSITORY: ${{ github.repository }}
