name: tests
run-name: Library unit-tests on different platforms and versions

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  unit-tests:
    strategy:
      matrix:
        node-version:
          - "16"
          - "18"
          - "20"
          - "21"
        platform:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install dependencies
      run: |
        npm ci
    - name: Lint with ESLint
      run: |
        npm run lint
    - name: Build TypeScript
      run: |
        npm run build
    - name: Test with Jest
      run: |
        npm test

